### ISSUE TITLE
DAR prints "building delta signature with block size" even when no --delta sig is specified

### ISSUE THREAD

**Issue by gulikoza** [Edrusb/DAR#10]
DAR outputs "building delta signature with block size" in verbose mode even when no --delta sig is specified.

I think this is only a display issue in save_inode().

For case cat_file::keep_hole the output is protected by if(delta_signature), for case cat_file::normal it's not.

**Comment by Edrusb** [comment]
Correct, should now be fixed, thanks for feedback! :)
