### ISSUE TITLE
dar-2.6.4-1 incorrect-fsf-address

### ISSUE THREAD

**Issue by lbazan** [Edrusb/DAR#12]
dar.x86_64: E: incorrect-fsf-address /usr/share/doc/dar/COPYING

libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/archive.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/archive5.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/archive_aux.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/archive_listing_callback.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/archive_num.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/archive_options.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/archive_options5.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/archive_options_listing_shell.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/archive_summary.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/capabilities.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/cat_status.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/compile_time_features.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/compression.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/compressor.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/crc.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/crit_action.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/criterium.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/crypto.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/data_tree.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/database.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/database5.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/database_archives.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/database_aux.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/database_listing_callback.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/database_options.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/datetime.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/deci.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/delta_sig_block_size.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/ea.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/entree_stats.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/entrepot.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/entrepot_libcurl.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/entrepot_libcurl5.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/entrepot_local.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/erreurs.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/etage.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/fichier_global.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/fichier_local.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/fsa_family.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/generic_file.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/get_version.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/gettext.h
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/gf_mode.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/infinint.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/int_tools.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/integers.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/libdar.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/libdar5.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/libdar_my_config.h
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/libdar_slave.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/libdar_xform.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/limitint.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/list_entry.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/mask.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/mask_list.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/mem_ui.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/memory_file.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/mycurl_protocol.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/path.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/proto_generic_file.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/range.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/real_infinint.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/secu_string.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/shell_interaction.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/shell_interaction_emulator.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/statistics.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/storage.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/thread_cancellation.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/tlv.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/tlv_list.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/tools.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/tuyau.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/user_interaction.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/user_interaction5.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/user_interaction_blind.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/user_interaction_callback.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/user_interaction_callback5.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/include/dar/wrapperlib.hpp
libdar-devel.x86_64: E: incorrect-fsf-address /usr/lib64/pkgconfig/libdar64.pc

**Comment by Edrusb** [comment]
can you check the latest commits, thanks

**Comment by lbazan** [comment]
thanks!
Cheers,

**Comment by Edrusb** [comment]
thanks for feedback!
