### ISSUE TITLE
dar-2.5.22 incorrect -G at man

### ISSUE THREAD

**Issue by igorzigorz** [Edrusb/DAR#14]
dar 2.5.22 man page
--single-thread, -G When libdar is compiled against libthreadar...

Must be --multi-thread ?

**Comment by Edrusb** [comment]
in dar 2.5.x when libdar is compiled with libthreadar by default multithread is used. -G let you ignore libthreadar presence and have a single threaded libdar. 
in dar.2.6.x even with libthreadar -G option is required to have libdar relying on multiple thread ... 

where from the change of name --single-thread in 2.5.x to --multi-thread in 2.6.x

it seems this change has not been documented
