### ISSUE TITLE
Feature request: pixz

### ISSUE THREAD

**Issue by yhaenggi** [Edrusb/DAR#15]
Could you implement pixz (https://github.com/vasi/pixz) into DAR? Having multi threaded compression would be much faster since its the main bottleneck. Its compatible with the standard xz implementation.

**Comment by Edrusb** [comment]
hello, pixz seems to be a command line tool without any API that would let libdar compress / decompress in memory. pixz seems to only work a plain files, while dar need working on file and on memory (before adding encryption, tape makes and putting into different slices/files) Without API, this is not possible to do so.
