### ISSUE TITLE
configure.ac uses AC_ARG_ENABLE and AC_ARG_WITH wrong most of the time

### ISSUE THREAD

**Issue by Polynomial-C** [Edrusb/DAR#18]
Hi,

I am co-maintaining the dar package in Gentoo Linux for a couple of years already any I always had problems with how poorly the configure.ac file of this project is written.
My main concern with it is its usage of `AC_ARG_ENABLE` and `AC_ARG_WITH`. 

Let me explain my concerns with an example:

Running `./configure --enable-ea-support` actually **disables** xattr support instead of enabling because `AC_ARG_ENABLE` is not being used correctly.

(I know, the default behavior is to enable xattr support so there's no need to submit this --enable switch to configure. But still the macros are being used wrong and I for example was massively confused when I started working on the dar package just to find out that some configure options don't behave like they are supposed to behave.)

Usually the macro needs to be used like this:
```
AC_ARG_ENABLE(option-name, help-string, action-if-present, action-if-not-present)
```
Where **action-if-present** represents the action that should be done if `configure` has been called with **either** `--enable-option` **or** `--disable-option` and **action-if-not-present** represents what should be done if `configure` has been called **without** this option at all.
The same applies to `AC_ARG_WITH` option.
There's a very fine written autotools-howto that explains options handling quite nicely: https://autotools.io/autoconf/arguments.html

Unfortunately this happens all over the configure.ac file. I haven't checked *all* configure options but those I checked all behave wrong if called with either the `--enable-...` or `--disable-...` switch.

While looking at the options handling, I also found usage of deprecated `AC_HELP_STRING` macro. This has been superseded by `AS_HELP_STRING` as can be seen here: https://www.gnu.org/software/autoconf//manual/autoconf-2.69/html_node/Obsolete-Macros.html#Obsolete-Macros

**Comment by Edrusb** [comment]
Hi,

Regarding you sentence "._..for a couple of years already any I always had problems with how poorly the configure.ac file of this project is written_": I note that after these many years you finally decided to get back to dar's project maintainer and in a such very polite way. That's very nice of you, congratulations.

Now, if you read the manual more carefully you will see that there is no --enable-ea-support expected to be given to the configure script, this has been obsoleted for more than ten years, now. Only --disable-ea-support exists. This is the same with other usual AC_ARG_ENABLE options. 

So I understand that you want to have the configure script to handle the case when a user invokes an unsupported --enable-* argument with a nice message telling him that such option does not exist and that the user should read more carefully the documentation? I can do that, no issue. Is that the main reason of your so lovely message?

About this sentence now: "_I for example was massively confused when I started working on the dar package just to find out that some configure options don't behave like they are supposed to behave._": First, I see no options to the configure script that don't behaves as they are supposed to behave. Second, in addition to the documentation I mentioned earlier, the "./configure --help" is here to help: it's straight forward, you should have read it if you had not found time to read the more completed documentation I have spent so much time to write and keep up to date.

I take note of your remark about AS/AC_HELP_STRING obsolescence and thank you for that. It will be fixes shortly.

Regards
Denis

**Comment by Polynomial-C** [comment]
Alright, I suppose I deserved your reply for my poorly chosen wording. I hereby want to apologize. I didn't mean to be impolite nor to insult you in any way.

Regarding the "*many years*" I've waited to get in touch with you... like I said, I am the co-maintainer of the Gentoo dar package and I always had the hope that our primary maintainer raises this issue. Perhaps he would even had come up with a better (non-impolite) wording.

Now coming back to my inital case:

I still think it would be beneficial if dar's configure.ac file uses `AC_ARG_ENABLE` and `AC_ARG_WITH` as it is intended by from autoconf upstream. Even though there's documentation for dar that imlplies there is no `--enable-this` or `--disable-that` configure option, the mere fact that the configure.ac file uses both macros means these options exist in the resulting configure script and produce false results. 

Even though I have messes up my initial inquiry, did you at least have a look at that autotools.io page? It really explains autotools handling very thoroughly and with nice well written examples.

From all the autotools-based open-source projects I maintain Gentoo packages, dar is the only one having such a huge non-standard behavior through its entire configure.ac file.
Other projects happily changed their configure.ac file once they got information about the non-standard behavior:
* https://github.com/sahlberg/libnfs/pull/261
* https://github.com/Irqbalance/irqbalance/pull/69
* https://github.com/legionus/kbd/pull/18

Last but not least, this would also provide a way to circumvent automagic dependencies which we at Gentoo want to avoid as much as possible. Resons as to why we are so eagerly trying to avoid automagic dependencies can be found here: [Gentoo Wiki - Automagic dependencies](https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies)

We sometimes even contribute code to avoid such cases:
* https://github.com/NetworkBlockDevice/nbd/pull/78


In case you still don't think this is worth the effort, I would like to humbly ask for your technical expertise on why you met that decision.

**Comment by Edrusb** [comment]
Apologies accepted. Now let's continue in a constructive way, OK?

Yes, I've read the https://autotools.io/autoconf/arguments.html document and there was no mistake in the way the different fields of AC_ARG_ENABLE and AC_ARG_WITH were used in dar. Just a lack of value exclusion providing an error message (here read "value" as this _--enable/disable-foo=value_). This lead one to be able to pass undocumented argument to ./configure without warning or error reported by the configure script.

Now let me explain the reason why the configure script is built that way:
dar has a lot of dependencies which are of different types:
- Features (libz, libbz2, liblzo2, libxz, libgcrypt, getxattr/lgetxattr system call, ioctl call for the nodump flag, st_birthtime field, librsync, libcurl, fadvise system call, upx, gpgme, libthreadar) 
- Operating system specific dependencies needed to build the software (libdl, gnugetopt, furtive-read) some for Solaris some for MACOS X and BSD style systems...
- pure options (examples, mode, debug, pedantic, build-html, profiling, debug-memory, python-binding)
- workarounds for some specific building problem cases (os-bits, fast-dir, thread-safe, execinfo, dar-static)

if dar had to impose all of the features, it would be a pain to many user that build them by hand from source code while they may not need all the features activated or do not want some to be activated like the libcurl network feature for example. At the opposite, having all of them disabled by default would lead to ask users to specify a long list of --enable-foo options. This would be a nightmare (as it was already the case 15 years ago with much less options).
 
The best approach was to activate all features that was possible to activate and provide a summary at then end for the user see what feature would be missing and letting them decide whether it worth the effort to add such missing library or not, when the corresponding feature was not of  interest for that particular user. So in spite of many requirements or many options to specify on command-line, I has been decided to do something more simple and flexible: you can just run ./configure the same as for many software that do not require any specific options, thing that is suitable for people that most of the time do not reading the boring documentation.

Now reading the "Gentoo Wiki - Automagic dependencies" I understand the problem, but I don't see why you need to have explicit options: "_When a package has automagic dependencies there are only two things that can be done: the first is to state the dependency as mandatory, no matter what the users put in their USE variable, but that might mean that some support that people don't want is always enable and its dependencies pulled in; **the other is to fix the build system to be able to disable at build time the dependency also if it's present on the system**_. 

Dar let you do both, the first is outside the scope of dar and we are back to the same problem explained above that lead to the current ./configure structure. The second is available to you, you have nothing to fix, you already have the ability to disable any of the "automagic" features.

What I can add now, is adding the --enable-foo option when there was only a --disable-foo option, to forcibly active any feature you want. Thus ./configure would fail if the requirement is not met. But I will not change the fact such feature will still be activated if no --enable/--disable option is specified for it,  and the feature get disabled it if its requirements are not met. Of course you will still have the possibility to forcibly disable any feature.

**Comment by Edrusb** [comment]
Hi, 

you should now have on branch_2.6.x several commits that provide the --enable-* options you requested.

The behavior is, for each feature:
- without any --enable/disable option, ./configure tries to enable it. If condition are not met it is disabled but configure succeeds (unless the feature cannot be bypassed, like the need of a C++ compiler).
- if the feature is explicitly enabled, the configure script will fail if not all prerequisite are met to enable it.
- if the feature is explicitly disabled, the configure script will not even try to enable it (as it was before).

for the already existing --enable-foo argument, using --disable-foo leads ./configure to abort with an error (because the feature is disabled by default).

Tell me if that totally fits your need
Denis

**Comment by Edrusb** [comment]
OK to close this issue?

**Comment by Polynomial-C** [comment]
I still think that `AC_ARG_ENABLE` and `AC_ARG_WITH` are not used correctly and would like to provide an alternative solution in a separate comment. I simply cannot write it up right now due to private duites...
Please bear with me for a bit longer.

**Comment by Polynomial-C** [comment]
Hi,

while dealing with my kids (sorry :smile:) I tried to write up a change on top of what you added to the branch_2.6.x which shows what I have in mind when speaking of "using AC_ARG_ENABLE correctly". Please have a look at my change 6562d463851ec80e8097dcf3674b39ccd939110f and tell me what you think about it. I might have messed up the indentation but that's nothing I couldn't fix. I also just changed two AC_ARG_ENABLE options because... well... see above :wink: 
I didn't have the time to test the changes so perhaps I have some typo hidden somewhere. What I am trying to show is that, while now using AC_ARG_ENABLE like the autoconf documentation suggests, it still retains what you were trying to achieve before (at least with the two options that I modified).

**Comment by Edrusb** [comment]
Hi Lars,

I understand your point of view, but it seems that autoconf has been simplified recently, according do the [gnu doc](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Package-Options.html): "_the shell variable enableval, [...] is actually just the value of the shell variable named enable_feature_ [...]". Thus assigning to _enable_libz_linking_ the value of _enableval_ is simply useless: it is already the case by default.

Second point, removing the explicit_libz_linking variable you won't be able to distinguish between the two different ./configure invocations:
- ./configure
- ./configure --enable-libz-linking=check

the first case should succeed in any case and trying to link with libz only if available
the second should fail and report an error when libz is not available

I can already hear some complaining about the fact that if the user took the time to write this somehow long sequence of characters "--enable-libz-linking=check" he should deserve attention and not just be ignored... even if this option is not documented ;^)

Regards,
Denis

**Comment by Edrusb** [comment]
feel free to reopen if needed
