### ISSUE TITLE
Requesting GnuPG key search not use email but instead generic string or just long-form UID

### ISSUE THREAD

**Issue by midnightmagic** [Edrusb/DAR#2]
I manually built and installed 2.5.x because it had access to the sha512 type; but when I tried to encrypt to my own key (which doesn't have an email address on it) it couldn't find the key. In the source I noticed that in crypto_asym.cpp:255 (or so) it compares only against the email address. Thus your users can't encrypt to even a long-form GnuPG UID.

Anyway, thanks for the nice software. Hope you have a pleasant weekend.

**Comment by Edrusb** [comment]
Well, there is still room for improvement, will see in the future how to rather target a key also based on its ID number

**Comment by Edrusb** [comment]
feature request added in the list 
https://sourceforge.net/p/dar/feature-requests/190/
