### ISSUE TITLE
[FEATURE] - snapcraft package

### ISSUE THREAD

**Issue by 030** [Edrusb/DAR#21]
**Not a bug? It's a feature?**
- For historical reasons, feature requests are managed from
https://sourceforge.net/p/dar/feature-requests/
- Check the feature you expect is not already in the list
- If a near feature is present fill free to add a comment rather than creating a new item
- if the same feature is present, just vote for it

https://snapcraft.io/

**Comment by Edrusb** [comment]
what the hell with that?

**Comment by yhaenggi** [comment]
snap from canonical has a proprietary server, so you get the lovely vendor lock-in.

**Comment by Edrusb** [comment]
OK, I now understand the request behind this obscure message, thanks @yhaenggi for your answer!

**Comment by Edrusb** [comment]
@030, I have added your feature request to https://sourceforge.net/p/dar/feature-requests/ as explained in the message you copied and passed here.
