### ISSUE TITLE
Bug report template refers to admin-only mailing list link

### ISSUE THREAD

**Issue by ryandesign** [Edrusb/DAR#27]
The bug report template says:

> **Before reporting a bug**
> - Check that what you intend to do is not clearly excluded in the documentation:
> http://dar.linux.free.fr/doc/man/index.html
> - Ask for support on dar-support mailing-list at 
> https://lists.sourceforge.net/lists/admin/dar-support

That list link is accessible by list administrators only. You should probably change that to a link that non-administrators can access.

**Comment by Edrusb** [comment]
Hi Ryan, 

will fix that shortly, thanks again for feedback!

Cheers,
Denis

**Comment by Edrusb** [comment]
fixed! 
Thanks for your feedback :+1:

**Comment by Edrusb** [comment]
closing the issue
