### ISSUE TITLE
error: no member named 'make_unique' in namespace 'std'

### ISSUE THREAD

**Issue by ryandesign** [Edrusb/DAR#28]
**Describe the bug**

Hi, I'm the maintainer of [dar in MacPorts](https://ports.macports.org/port/dar) and trying to update it to version 2.7.0 fails:

```
crypto_sym.cpp:260:18: error: no member named 'make_unique' in namespace 'std'
            return std::make_unique<crypto_sym>(*this);
                   ~~~~~^
crypto_sym.cpp:260:30: error: 'crypto_sym' does not refer to a value
            return std::make_unique<crypto_sym>(*this);
                                    ^
./crypto_sym.hpp:66:11: note: declared here
    class crypto_sym : public crypto_module
          ^
2 errors generated.
```

From what I can determine, `make_unique` is a C++14 feature, but your configure script only checks for C++11 features and uses the `-std=c++11` flag if needed. You should update configure.ac to check for C++14 features and use `-std=c++14` if needed.

**To Reproduce**
Build dar 2.7.0 with a compiler that defaults to pre-C++14 mode, such as clang, at least the a-few-years-old version of clang I use that comes with Xcode 9.4.1.

**Expected behavior**
Successful build

**Screenshots**
n/a

**Software used:**
dar 2.7.0

**Operating system used:**
macOS 10.13.6

**Additional context**
n/a

**Comment by ryandesign** [comment]
Just to confirm, adding `-std=c++14` to CXXFLAGS allowed the build to succeed.

**Comment by Edrusb** [comment]
Hi Ryan,

Thank you for this feedback. You are correct, std::make_unique only exists since C++14, I missed paying attention to that in the configure script. As you have found a workaround and due to the load of building a new version (not just the source packaging but all that comes with like windows binay, website update ...) I will wait a couple of weeks to make 2.7.1 with that fix unless other important problem are met. I hope you'll understand. In the meanwhile this issue stays open for other to refer to in case they hit it also.

Best Regards,
Denis

**Comment by ryandesign** [comment]
Certainly! Just wanted to make sure you're aware of the issue so that it can be fixed for the next release, whenever that is.

**Comment by Edrusb** [comment]
The clang I have access to does not cause any problem. I guess it is not old enough to not support C++14. 

Anyway, I have built a source package 2.7.1.RC1 (release candidate 1), which you can fetch from [here](https://dar.edrusb.org/dar.linux.free.fr/Interim_releases/) 

If you have the opportunity to test it for the problem you reported, I'd be glad having your feedback!

Cheers,
Denis

**Comment by ryandesign** [comment]
Thanks, but you should also change the test program. Even after 71c83f98120c620aede9d7ed2338f8043c5c5d79 the test program is still just `thread_local static int test = 0;` which only tests for a C++11 feature. You should change this to test for a C++14 feature (and if there are any optional aspects of the C++14 standard, and if you rely on any of those, you should test for those especially). Otherwise, anyone who has a compiler that defaults to C++11 mode will get the erroneous configure output `checking for c++14 support... yes` and will still experience build failure. This can be simulated by adding `-std=c++11` to CXXFLAGS when configuring.

**Comment by Edrusb** [comment]
Yep I just figured it out, was going too quickly yesterday...

**Comment by Edrusb** [comment]
Here it is, 2.7.1.RC2 available [here](https://dar.edrusb.org/dar.linux.free.fr/Interim_releases/)  should behave better for this problem I hope. Thanks again for your appreciated feedback!

**Comment by Edrusb** [comment]
the just release 2.7.1 should have this fixed now, closing this issue
