### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by dasJ** [Edrusb/DAR#3]
Hey,

1.5.x is now out for a long time, what are the plans for 1.6? Is there any planned date or a roadmap?
Thanks

**Comment by Edrusb** [comment]
Hi,

there has been a lot of release since 1.5.x I guess you just missed it :-)
http://dar.linux.free.fr/ for more

**Comment by dasJ** [comment]
Oh, 2.5.x of course :laughing:

**Comment by dasJ** [comment]
Thanks a million!
