### ISSUE TITLE
Can't build 2.7.2 + libthreadar with clang on FreeBSD

### ISSUE THREAD

**Issue by igorzigorz** [Edrusb/DAR#34]
Can't build dar 2.7.2 and libthreadar 1.3.3 under FreeBSD.
There is no problem with version 2.6.15 or without libthreadar.
clang 11.0.1

--- get_version.lo ---
In file included from get_version.cpp:76:
In file included from ./parallel_tronconneuse.hpp:44:
In file included from ./heap.hpp:37:
In file included from /usr/local/include/libthreadar/libthreadar.hpp:52:
/usr/local/include/libthreadar/barrier.hpp:75:19: warning: explicitly defaulted move assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
        barrier & operator = (barrier && ref) noexcept = default;
                  ^
/usr/local/include/libthreadar/barrier.hpp:93:21: note: move assignment operator of 'barrier' is implicitly deleted because field 'val' is of const-qualified type 'const unsigned int'
        const unsigned int val;
                           ^
-- get_version.lo ---
In file included from get_version.cpp:69:
In file included from ./erreurs.hpp:32:
/usr/include/c++/v1/deque:279:34: error: invalid application of 'sizeof' to an incomplete type 'libdar::crypto_worker'
  static const _DiffType value = sizeof(_ValueType) < 256 ? 4096 / sizeof(_ValueType) : 16;
                                 ^~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/deque:289:32: note: in instantiation of template class 'std::__1::__deque_block_size<libdar::crypto_worker, long>' requested here
                               __deque_block_size<_ValueType, _DiffType>::value
                               ^
/usr/include/c++/v1/deque:956:13: note: in instantiation of default argument for '__deque_iterator<libdar::crypto_worker, libdar::crypto_worker *, libdar::crypto_worker &, libdar::crypto_worker **, long>' required here
    typedef __deque_iterator<value_type, pointer, reference, __map_pointer,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/deque:1269:15: note: in instantiation of template class 'std::__1::__deque_base<libdar::crypto_worker, std::__1::allocator<libdar::crypto_worker>>' requested here
    : private __deque_base<_Tp, _Allocator>
              ^
./parallel_tronconneuse.hpp:231:35: note: in instantiation of template class 'std::__1::deque<libdar::crypto_worker, std::__1::allocator<libdar::crypto_worker>>' requested here
        std::deque<crypto_worker> travailleur;
                                  ^
./parallel_tronconneuse.hpp:60:11: note: forward declaration of 'libdar::crypto_worker'
    class crypto_worker;
          ^
./parallel_tronconneuse.hpp:132:61: error: cannot initialize object parameter of type 'const libdar::generic_file' with an expression of type 'const libdar::parallel_tronconneuse'
        virtual infinint get_position() const override { if(is_terminated()) throw SRC_BUG; return current_position; };
                                                            ^~~~~~~~~~~~~
./parallel_tronconneuse.hpp:140:56: error: cannot initialize object parameter of type 'const libdar::generic_file' with an expression of type 'libdar::parallel_tronconneuse'
        virtual void write_end_of_file() override { if(is_terminated()) throw SRC_BUG; sync_write(); };
                                                       ^~~~~~~~~~~~~
./parallel_tronconneuse.hpp:140:88: error: cannot initialize object parameter of type 'libdar::generic_file' with an expression of type 'libdar::parallel_tronconneuse'
        virtual void write_end_of_file() override { if(is_terminated()) throw SRC_BUG; sync_write(); };
                                                                                       ^~~~~~~~~~
--- get_version.lo ---
2 warnings and 4 errors generated.
*** [get_version.lo] Error code 1

**Comment by Edrusb** [comment]
Hi, problem should now be fixed using release 1.3.4 of libthreadar I have just done with the fix for this problem. 
I could compile dar+libthreadar under FreeBSD 12.2-RELEASE-p7 

Don't hesitate to reopen this issue (or to create another as you prefer) if you still face a problem with dar or libthreadar
By the way, thanks for your feedbacks!

**Comment by Edrusb** [comment]
compilation successful for dar 2.7.2 under FreeBSD 13:

> FreeBSD13 | ~/dar-2.7.2 >src/dar_suite/dar -V
> Warning: using insecure memory!
> 
>  dar version 2.7.2, Copyright (C) 2002-2021 Denis Corbin
>    Long options support         : YES
> 
>  Using libdar 6.4.1 built with compilation time options:
>    gzip compression (libz)      : YES
>    bzip2 compression (libbzip2) : YES
>    lzo compression (liblzo2)    : YES
>    xz compression (liblzma)     : YES
>    zstd compression (libzstd)   : YES
>    lz4 compression (liblz4)     : YES
>    Strong encryption (libgcrypt): YES
>    Public key ciphers (gpgme)   : YES
>    Extended Attributes support  : NO
>    Large files support (> 2GB)  : YES
>    ext2fs NODUMP flag support   : NO
>    Integer size used            : 64 bits
>    Thread safe support          : YES
>    Furtive read mode support    : NO
>    Linux ext2/3/4 FSA support   : NO
>    Mac OS X HFS+ FSA support    : YES
>    Linux statx() support        : NO
>    Detected system/CPU endian   : little
>    Posix fadvise support        : YES
>    Large dir. speed optimi.     : YES
>    Timestamp read accuracy      : 1 nanosecond
>    Timestamp write accuracy     : 1 nanosecond
>    Restores dates of symlinks   : YES
>    Multiple threads (libthreads): YES (1.3.4)
>    Delta compression (librsync) : YES
>    Remote repository (libcurl)  : YES
>    argon2 hashing (libargon2)   : YES
> 
>  compiled the Oct 16 2021 with GNUC version 10.3.0
>  dar is part of the Disk ARchive suite (Release 2.7.2)
>  dar comes with ABSOLUTELY NO WARRANTY; for details
>  type `dar -W'. This is free software, and you are welcome
>  to redistribute it under certain conditions; type `dar -L | more'
>  for details.
> 
> FreeBSD13 | ~/dar-2.7.2 >uname -a
> FreeBSD FreeBSD13 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
> FreeBSD13 | ~/dar-2.7.2 >

**Comment by igorzigorz** [comment]
It also affects MacOS.

If add to erreurs.hpp (Fix deque iterator type in order to support incomplete types.):

#define _LIBCPP_ABI_INCOMPLETE_TYPES_IN_DEQUE

Then next error:

-- parallel_tronconneuse.lo ---
In file included from parallel_tronconneuse.cpp:28:
In file included from ./parallel_tronconneuse.hpp:39:
In file included from /usr/include/c++/v1/string:506:
In file included from /usr/include/c++/v1/string_view:175:
In file included from /usr/include/c++/v1/__string:57:
In file included from /usr/include/c++/v1/algorithm:643:
/usr/include/c++/v1/memory:3455:7: error: exception specification of overriding function is more lax than base version
class __shared_ptr_emplace
      ^
/usr/include/c++/v1/memory:4291:26: note: in instantiation of template class 'std::__1::__shared_ptr_emplace<libthreadar::barrier, std::__1::allocator<libthreadar::barrier>>' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
parallel_tronconneuse.cpp:102:15: note: in instantiation of function template specialization 'std::__1::make_shared<libthreadar::barrier, unsigned long>' requested here
            waiter = make_shared<barrier>(num_workers + 2); // +1 for crypto_reade thread, +1 this thread
                     ^
/usr/include/c++/v1/memory:3364:13: note: overridden virtual function is here
    virtual ~__shared_weak_count();
            ^
1 warning and 1 error generated.
*** [parallel_tronconneuse.lo] Error code 1

**Comment by Edrusb** [comment]
2.7.2 code compiles fine with clan under Linux...

**Comment by Edrusb** [comment]
I had to upgrade libthreadar (use 1.3.5 or more recent under FreeBSD) to get dar compiling under FreeBSD 13 using clang. 

Though there is a bug in the autoconf tool (the one that generates the configure script from dar's configure.ac specifications) that lead it to detect libintl.h in /usr/local/include but not passing the -I/usr/local/include to the C and C++ compilation lines for dar and libdar.

You can workaround this doing the following (using csh):

setenv CXXFLAGS -I/usr/local/include
setenv CFLAGS $CXXFLAGS
./configure [...]
make [...]

or using a bourne shell:

export CXXFLAGS=-I/usr/local/include
export CFLAGS=$CXXFLAGS
./configure [...]
./make [...]

Feel free to reopen this case if necessary
Cheers,
Denis
