### ISSUE TITLE
incompatible windows file names e.g. 'src/check/Old_format/archive_08-1_crypto_bf:test.1.dar' 

### ISSUE THREAD

**Issue by Micke3rd** [Edrusb/DAR#36]
Hi,
I tried to clone the current version for a build .... but with errors, presumably because a few file names are incompatible with the char ":"
Would like to request to replace it.

Regards Micke

**Comment by Edrusb** [comment]
Hi, 

this is done, you should now be able to "git clone" under windows. 
If there is still issues, feel free to reopen this report

Cheers,
Denis
