### ISSUE TITLE
Same slice is created/written multiple times with -E option

### ISSUE THREAD

**Issue by tomtor** [Edrusb/DAR#37]
**Describe the bug**

I have a script that dumps a file system and uploads it to google drive with the script `bupload.sh`:

```
DATE=`date +%y%m%d`

DDIR=/media/bc4/dumps

rm $DDIR/*dar*

dar -R / -z -s 1G -D -c $DDIR/$DATE.swan20-root-0 -P media -P snap -P var -P boot -P mnt -P tmp -P proc -P dev -P var/lib/docker/aufs -P var/lib/lxcfs -P run -P sys -P export --min-digits 5,5,5 -E 'bupload.sh "swan20-Dumps" %p/%b.%N.dar'
```

This used to work fine, but recently I discovered that some slices are written multiple times!

eg slice 00024:

```
...
DONE /media/bc4/dumps/220202.swan20-root-0.00022.dar
DONE /media/bc4/dumps/220202.swan20-root-0.00023.dar
DONE /media/bc4/dumps/220202.swan20-root-0.00024.dar
DONE /media/bc4/dumps/220202.swan20-root-0.00025.dar
DONE /media/bc4/dumps/220202.swan20-root-0.00024.dar
...
```

I noticed this since using bigger 1G slices, 256M slices worked fine, but this is probably not related.

**Software used:**
2.7.x branch

**Operating system used:**
- Ubuntu 20.04

**Comment by Edrusb** [comment]
Hi, this is probably not a bug but the fact that either:

- dar tries to resave a file uncompressed when it take more place uncompressed than compressed
- dar tries to resave a file that has changed at the time it was read for backup
this would here concern a file larger than a slice

to validate this hypothesis, you can get the backup content by slide using`dar -l <archive> -Tslice` and look at the file that is saved in slice 24

you can then either exclude it from compression (see either -P option for example, but there is also -X and -] option that can help here too), or you can instruct dar not to try resaving files when they changed (see --retry-on-change option)

let me know about your findings

**Comment by tomtor** [comment]
> dar tries to resave a file uncompressed when it take more place uncompressed than compressed

That slice indeed contains a large collection of `.bz2` files. I am now rerunning the script with `--retry-on-change 0` added.

**Comment by Edrusb** [comment]
you'd better use -X "*.bz2" : this will also save you CPU cycles not trying compress already compressed files

more generally there is a user target named "compress-exclusion" and defined in darrc (usually located in /etc or /usr/local/etc depending on the way dar has been installed)  which is the consolidation of many users feedback about files not interesting to try to compress. You could leverage it and keep --retry-on-change to its default value, as you probably would like to avoid dirty files (files that changed at the time they were saved) as much as possible.

**Comment by tomtor** [comment]
> you'd better use -X "*.bz2" : this will also save you CPU cycles not trying compress already compressed files

Ok, thanks for the feedback!

`--retry_on_change 0` still resulted in a repeated slice, so now trying with `-X "*.bz2"`

**Comment by tomtor** [comment]
> `--retry_on_change 0` still resulted in a repeated slice, so now trying with `-X "*.bz2"`

`-X "*.bz2"` solves the issue.

**Comment by Edrusb** [comment]
ok, thanks for this feedback!
