### ISSUE TITLE
Bug in cache.cpp

### ISSUE THREAD

**Issue by klaviermann** [Edrusb/DAR#39]
---- exception type = [BUG] ----------
[source]
	File cache.cpp line 562 : it seems to be a bug here
	stack dump : /lib/x86_64-linux-gnu/libdar64.so.6000(_ZN6libdar4EbugC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0x113) [0x7f88d298ac33]
	stack dump : /lib/x86_64-linux-gnu/libdar64.so.6000(+0x52bc9) [0x7f88d28c9bc9]
	stack dump : /lib/x86_64-linux-gnu/libdar64.so.6000(_ZN6libdar6escape18inherited_truncateERKNS_8limitintImEE+0x4b) [0x7f88d298f63b]
	stack dump : /lib/x86_64-linux-gnu/libdar64.so.6000(+0x13fac7) [0x7f88d29b6ac7]
	stack dump : /lib/x86_64-linux-gnu/libdar64.so.6000(_ZN6libdar17filtre_sauvegardeERKSt10shared_ptrINS_16user_interactionEERKNS_4maskES7_RKNS_15pile_descriptorERNS_9catalogueERKSB_RKNS_4pathEbbbbbRNS_10statisticsEbS7_S7_RKNS_8limitintImEEbSN_bbRKNS_14filesystem_idsENS_17comparison_fieldsEbbbSN_SN_SN_SN_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_bRKSt3setINS_10fsa_familyESt4lessIS11_ESaIS11_EESZ_bSN_S7_bbRKS10_ISX_S12_ISX_ESaISX_EENS_23modified_data_detectionERKNS_20delta_sig_block_sizeE+0xb44) [0x7f88d29aa2d4]
	stack dump : /lib/x86_64-linux-gnu/libdar64.so.6000(_ZN6libdar7archive9i_archive16op_create_in_subENS1_9operationERKNS_4pathERKSt10shared_ptrINS_8entrepotEEPNS_9catalogueEPKSB_bRKNS_4maskESH_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESP_bRKNS_11crit_actionEbbbbbbRKNS_8limitintImEEbNS_11compressionEmmSW_SW_SH_SP_NS_11crypto_algoERKNS_11secu_stringEjRKSt6vectorISN_SaISN_EES16_SH_SW_bSP_SW_bbbRKNS_14filesystem_idsENS_17comparison_fieldsEbbbSW_SP_SW_SW_bbbSW_SP_NS_9hash_algoESW_SP_SH_bRKSt3setINS_10fsa_familyESt4lessIS1D_ESaIS1D_EEmmbbSH_SW_bbRKS1C_ISN_S1E_ISN_ES13_ENS_23modified_data_detectionESW_S1B_RKNS_20delta_sig_block_sizeEPNS_10statisticsE+0xe96) [0x7f88d29ca716]
	stack dump : /lib/x86_64-linux-gnu/libdar64.so.6000(_ZN6libdar7archive9i_archive12op_create_inENS1_9operationERKNS_4pathERKSt10shared_ptrINS_8entrepotEEPS0_RKNS_4maskESE_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESM_bbbbbbbRKNS_8limitintImEEbNS_11compressionEmmSQ_SQ_SE_SM_NS_11crypto_algoERKNS_11secu_stringEjRKSt6vectorISK_SaISK_EES10_SE_SQ_bSM_SQ_bbbRKNS_14filesystem_idsENS_17comparison_fieldsEbbSQ_SM_SQ_SQ_bbSQ_SM_NS_9hash_algoESQ_SM_SE_bRKSt3setINS_10fsa_familyESt4lessIS17_ESaIS17_EEmmbbSE_SQ_bbRKS16_ISK_S18_ISK_ESX_ENS_23modified_data_detectionESQ_S15_RKNS_20delta_sig_block_sizeEPNS_10statisticsE+0xa84) [0x7f88d29cc4a4]
	stack dump : /lib/x86_64-linux-gnu/libdar64.so.6000(_ZN6libdar7archive9i_archiveC2ERKSt10shared_ptrINS_16user_interactionEERKNS_4pathES9_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESH_RKNS_22archive_options_createEPNS_10statisticsE+0xf0a) [0x7f88d29c277a]
	stack dump : /lib/x86_64-linux-gnu/libdar64.so.6000(_ZN6libdar7archiveC1ERKSt10shared_ptrINS_16user_interactionEERKNS_4pathES8_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESG_RKNS_22archive_options_createEPNS_10statisticsE+0x123) [0x7f88d2944933]
	stack dump : dar(+0x4a212) [0x556df8bf9212]
	stack dump : dar(+0x54bb9) [0x556df8c03bb9]
	stack dump : /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f88d23d9d90]
	stack dump : /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f88d23d9e40]
	stack dump : dar(+0x20935) [0x556df8bcf935]
[most outside call]
-----------------------------------

INTERNAL ERROR, PLEASE REPORT THE PREVIOUS OUTPUT TO MAINTAINER

Ubuntu 22.04.01 LTS

dar version 2.7.3, Copyright (C) 2002-2022 Denis Corbin
   Long options support         : YES

 Using libdar 6.4.2 built with compilation time options:
   gzip compression (libz)      : YES
   bzip2 compression (libbzip2) : YES
   lzo compression (liblzo2)    : YES
   xz compression (liblzma)     : YES
   zstd compression (libzstd)   : YES
   lz4 compression (liblz4)     : YES
   Strong encryption (libgcrypt): YES
   Public key ciphers (gpgme)   : YES
   Extended Attributes support  : YES
   Large files support (> 2GB)  : YES
   ext2fs NODUMP flag support   : YES
   Integer size used            : 64 bits
   Thread safe support          : YES
   Furtive read mode support    : YES
   Linux ext2/3/4 FSA support   : YES
   Mac OS X HFS+ FSA support    : NO
   Linux statx() support        : YES
   Detected system/CPU endian   : little
   Posix fadvise support        : YES
   Large dir. speed optimi.     : YES
   Timestamp read accuracy      : 1 nanosecond
   Timestamp write accuracy     : 1 nanosecond
   Restores dates of symlinks   : YES
   Multiple threads (libthreads): NO 
   Delta compression (librsync) : NO
   Remote repository (libcurl)  : NO
   argon2 hashing (libargon2)   : YES

 compiled the Jan  3 2022 with GNUC version 11.2.0
 dar is part of the Disk ARchive suite (Release 2.7.3)

**Comment by Edrusb** [comment]
this seems to be related to this fix/commit: 
https://github.com/Edrusb/DAR/commit/f9a9499994ce9b804300ec75d9093e06263c70ae released in 2.6.16
