### ISSUE TITLE
missing precision in (stored?/)restored file times

### ISSUE THREAD

**Issue by calestyo** [Edrusb/DAR#4]
Hi.

Using:  dar 2.5.15 and libdar 5.12.2 I've followed the basic examples for backup/restore from the tutorial,

I noticed that some precision of the file times was lost:
e.g.
`6758015 -rw-r--r-- 1 1000 1000 1000 ?        4 2018-07-11 22:49:28.728542758 +0200 file`
vs.
`6758275 -rw-r--r-- 1 1000 1000 1000 ?        4 2018-07-11 22:49:28.728542000 +0200 file`

I.e. the final 3 digits aren't stored.

Can this be somehow done? And shouln't dar at leas give a warning if such data is lost? :-)

Best wishes,
Chris

**Comment by calestyo** [comment]
Hey...

Seems your account here was unavailable some time and I've reported this in the meantime here:
https://sourceforge.net/p/dar/bugs/204/

It's likely the ms limitation then... which makes this a feature request to support the full range which nowadays at least most linux filesystems seem to do.

One reasons is that it's simply "ugly" to loose that information... another one is that it confuses other tools which work on the nano-second resolution.
In the report over at sourceforge I brought rsync as an example, which now thinks the restored files are different from the originals, because of the different times.

As for portability... well sure,... nothing is 100% portable, but don't you e.g. already use non-portable syscalls to get things like FSA?

Best wishes,
Chris.

**Comment by Edrusb** [comment]
feature requested added in the list
https://sourceforge.net/p/dar/feature-requests/189/
