### ISSUE TITLE
Recursion in block_compressor::skip_relative?

### ISSUE THREAD

**Issue by Sviat89** [Edrusb/DAR#41]
Sorry if I'm wrong.
Looks like it should be
`return compressed->skip_relative(x);`
instead of 
`return skip_relative(x);`

**Comment by Edrusb** [comment]
seems you are correct, and hopefully this call does not seem to be used in libdar, else it would make an endless loop!
Will double check and confirm you shortly.

**Comment by Edrusb** [comment]
at first sight there is only 3 places where the skip_relative() method is used (and not only implemented to satisfy the parent class interface):
-  class elastic (elastic buffer are used with encryption and are never compressed thus the bug cannot expresses this way
- class sparse_file (but this is when restoring a file stored a sparse file to a filesystem, using the sparse_file::copy_to, the target over which sparse file copies is usually a plain file object (class fichier_local) and not a compressed object)
- class terminator (it is never compressed...)

maybe I missed something but hopefully the bug you've found has very little chance to be hit. I will fix that anyway, but this does not trigger a new release hopefully! 
Thanks for your feedback!

**Comment by Edrusb** [comment]
code is updated on branch_2.7.x (will be merged to master branch after next release)

**Comment by Edrusb** [comment]
closing report as fix is now released within version 2.7.9
