### ISSUE TITLE
On-fly isolated catalogue excludes delta signatures

### ISSUE THREAD

**Issue by AndrolGenhald** [Edrusb/DAR#42]
I just noticed that using `--aux` to create an on-fly isolated catalogue in combination with the `--delta sig` option fails to include the delta signatures in the isolated catalogue.

I also tried using `--include-delta-sig "*"` since the man page says that it will cause isolation operations to compute missing delta signatures, but that didn't help either (it doesn't seem like it should be necessary either since the delta signature should already be part of the original archive).

I have my backups set up so that the isolated catalogue is created on the fly and stored on the local machine, while the backup itself is encrypted with a GPG key unavailable to the local machine and stored remotely. The on-fly isolated catalogue allows me to do incremental backups, but since the `--delta sig` option doesn't seem to be working for the isolated catalogue, it prevents me from using the binary delta feature.

**Comment by Edrusb** [comment]
this is expected as indicated from the man page:
`Delta signature transfer is not possible for on-fly isolation, you need to do normal archive isolation to obtain an isolated catalogue with delta signatures.`

source: http://dar.linux.free.fr/doc/man/index.html

**Comment by Edrusb** [comment]
The underlying reason is that the created backup is not closed (though it is completely written to disk) when performing the on-fly isolation: its catalogue (table of content) is readable from memory and used for the onfly isolation, but some operations like fetching signature would need to skip back and _read_ data from the backup which is still at that time a write-only object. To have the ability to perform what you want to do, dar should close the backup object and reopen it in read mode thus loading its catalogue from disk to memory and from there when needed, fetch delta signatures from the now readable backup, this would not be anymore 'on-fly' and would not bring any advantages compared to doing the isolation after the backup.

thi

**Comment by AndrolGenhald** [comment]
Oh, I missed that part of the man page, sorry!

Yeah, that limitation makes sense. I misunderstood how the on-fly isolation worked, I thought it was creating the isolated catalogue in parallel with the backup, rather than after the backup was fully written to disk. That also explains why I wasn't seeing the isolated catalogue created until after the backup was almost finished, which had surprised me.

It does seem like my use case is the only edge case where this doesn't work quite as well, since the symmetric key for the backup only exists in memory while dar is running, and once dar finishes the backup it's no longer possible to retrieve the symmetric key since it's already been encrypted with the public key and wiped from memory, and the private key isn't accessible. I'll just have to find some other way to achieve what I want.

Thanks for explaining!

**Comment by Edrusb** [comment]
for backup creation, dar produce the backup in sequence, in particular, it can produce the backup to its standard output (except if slicing is done, but this can be done afterward or at the time the data reaches the disk using dar_xform) 

in other words if you want to, you should be able to do something like this:

`mkfifo to_isolation.1.dar`

in a first terminal prepare to the isolation
`dar -C CAT_backup -A to_isolation --sequential-read -w -z -J toto -K tutu`

in a second terminal perform the backup which will both write to disk and at the same time send data to the first command for isolation:

`dar -c - -z -K toto -R /<somepath> -g <something> | tee -a to_isolation.1.dar > backup.1.dar`

I though I could also pipe the output to dar_xform in place of backup1.1.dar to set slicing at the time the data reaches the disk but it fails, though it should not, I will check why...

you end with this:
```
>ls -al
total 11992
drwxr-xr-x  2 denis maison     4096  2 févr. 14:19 .
drwxr-xr-x 13 denis maison  1241088  2 févr. 14:05 ..
-rw-r--r--  1 denis maison 10789489  2 févr. 14:14 backup.1.dar
-rw-r--r--  1 denis maison   236107  2 févr. 14:14 CAT_backup.1.dar
prw-r--r--  1 denis maison        0  2 févr. 14:05 to_isolation.1.dar
```
can remove the named pipe and use the backup and CAT_backup (isolated catalogue) as usual:

```
dar -l backup -q | egrep '^total|^ - '
Warning: using insecure memory!
Archive backup requires a password: 
total number of inode : 5955
 - directories        : 496
 - plain files        : 4531
 - symbolic links     : 928
 - named pipes        : 0
 - unix sockets       : 0
 - character devices  : 0
 - block devices      : 0
 - Door entries       : 0
 - number of inode with hard link           : 0
 - number of reference to hard linked inodes: 0
```

```
>dar -l CAT_backup -q | egrep '^total|^ - '
Warning: using insecure memory!
Archive CAT_backup requires a password: 
total number of inode : 5955
 - directories        : 496
 - plain files        : 4531
 - symbolic links     : 928
 - named pipes        : 0
 - unix sockets       : 0
 - character devices  : 0
 - block devices      : 0
 - Door entries       : 0
 - number of inode with hard link           : 0
 - number of reference to hard linked inodes: 0
```

**Comment by AndrolGenhald** [comment]
I got close to getting something working using pipes, but I ran into the problem that "delta signature is disabled when the archive of reference is read in sequential mode".

**Comment by Edrusb** [comment]
Arf... yes. This limitation is due to the fact delta signatures are too big to hold in the catalogue and for a given file under backup, looking for the delta signature (of reference) may implies seeking backward in the backup (which is not possible in sequential read mode), depending on the order the directory is read compared to the order it has been stored the first time...  Well, I have no other idea then with the options you use to make it in two phases, backup, then catalogue isolation.

**Comment by Edrusb** [comment]
the directory read order is strongly dependent on the operating system and mostly the filesystem underneath... usually commands like 'ls' reorder alphabetically or by last modification time in memory what the system provided, before displaying the content.
