### ISSUE TITLE
[Question] which zstd version in DAR?

### ISSUE THREAD

**Issue by jumbi77** [Edrusb/DAR#43]
I know zstd is integrated into DAR a while ago. Zstd development is still active - current version is v1.5.2 ([0]). Besides performance improvements there are also some security fixex, e.g. ([1]). Just curious if DAR integrated an own zstd implemention (if yes what version) or uses kernel version?

[0]: https://github.com/facebook/zstd/releases
[1]: https://www.mend.io/vulnerability-database/WS-2021-0184?query=zstd

After answering, feel free to close this.
Much thanks in advance.

**Comment by Edrusb** [comment]
Dar relies on libzstd (see http://dar.linux.free.fr/doc/from_sources.html for all direct and mostly optional dependencies).
As such, it does not include any zstd algo code, but make calls to this library, which version depend on the operating system/distro version. For dynamic dar binary, upgrading your disto for a bug fix in libzstd will automatically let dar get this fix. For statically linked binaries (like dar_static) it is a matter of recompiling against the new libzstd version, in that case the distribution will/should provide an new version of the dar_static binary.

**Comment by jumbi77** [comment]
Much thanks for the clarification.
