### ISSUE TITLE
Feature request: compress together multiple small files

### ISSUE THREAD

**Issue by shaicoleman** [Edrusb/DAR#58]
DAR compresses poorly well when there are a lot of small files compared to tar (e.g. double the size for my app's node_modules)

If small files were concatenated before compression (especially if intelligently sorted by extension), the compression ratio would significantly improve.

Small files should be arranged into independant blocks which would work like mini tar files.
The block size should be configurable. Bigger blocks would allow for better compression ratio at the expense of slower access time.

RAR implements something similar, and calls it solid archives
https://documentation.help/WinRAR/HELPArcSolid.htm

**Comment by Edrusb** [comment]
Yes, this is something known and due to design decision.

Why sorting files by extension would improve significantly the compression ratio? 

If you rely on blocks of fixed size (once user has chosen the size), how to you managed to have those block not containing garbage? In other words, what if the file sizes do not fit exactly at block boundary? Do you split a file in two? Do you add garbage in the last block? How then do you remember where is the data of each file?

RAR "solid archives" seems to be exactly as what tar does for compression (well tar does not compress itself, but other too compress tar's output)

The problem of doing so is that it makes your backup fragile to data corruption (you lose all data following data corruption). This is the reason why dar compresses per file (design decision as mentioned above). 

The second problem doing so is the time required to restore a single or even a few files: you need to spend the time to read the whole backup, which can be several terabytes even if you file is only a few tens of bytes.

**Comment by shaicoleman** [comment]
> Why sorting files by extension would improve significantly the compression ratio?
Compression works by blocks, if you put more repetitive data in the same block, the compression ratio would improve.
See https://github.com/zholos/tar-sorted 
Also RAR solid archive sort by extension for the same reason. Also some extensions aren't compressible.

> What if the file sizes do not fit exactly at block boundary?
* Option 1: split the file into multiple blocks
* Option 2: only put whole files into a block. If adding a file to the block goes over the block, start a new block. Big files may either be split, or have a block that contains one file.

> RAR "solid archives" seems to be exactly what tar does for compression
* Yes, that's an important tar functionality. It's difficult to justify the switching cost from tar, if it performs worse on that aspect.

> how do you managed to have those blocks not containing garbage?
* Option 1: store the file size, and have variable block size. If there's no more space in the block, start a new block.
* Option 2: zero pad the block (very compressible)

> The problem of doing so is that it makes your backup fragile to data corruption
* The blocks should be independent, so you should only lose the files in that block. The bigger the block size, the more data you'll lose.

> The second problem doing so is the time required to restore a single or even a few files: you need to spend the time to read the whole backup
* The blocks should be independent, so you should be able to read only the blocks containing the data

The other concern is adding/modifying/deleting files, and there are two approaches:
* Recompressing the whole file (slow)
* Variable block size (non optimal compression)

**Comment by Edrusb** [comment]
> > Why sorting files by extension would improve significantly the compression ratio?
> 
>     * Compression works by blocks,

this depends on algorithms:
[gzip](https://en.wikipedia.org/wiki/Gzip)
[LZ77](https://en.wikipedia.org/wiki/LZ77_and_LZ78#LZ77)
[Stream-Based Lossless Data Compression ](https://link.springer.com/chapter/10.1007/978-981-16-4095-7_16)
and so on...

Some implementations compress per block, usually this is by splitting the input data in **fixed sized** block and then performing a stream compression on each of them, resetting the compression engine at each new block, which reduces compression ratio, but give the ability to decompress passed a data corruption (what dar does per file)

[The Block Lossless Data Compression Algorithm](http://paper.ijcsns.org/07_book/200910/20091015.pdf)


> if you put more repetitive data in the same block, the compression ratio would improve.

The same extension between two files does not imply repetitive pattern in much cases... this is really dependent on the nature of the data to compress, for example jpeg images the ones you take with your phone have no repetitive pattern between them... same with audio files... avi is even worse as it contains different type of codecs... There is just text based file (pdf/txt/dvi/... ) and other repetitive formats (which usually compress well) that could leverage such file reordering... at what performance (execution time) penalty...

> > What if the file sizes do not fit exactly at block boundary?
> 
>     * Option 1: split the file into multiple blocks
> 
>     * Option 2: only put whole files into a block. If adding a file to the block goes over the block, start a new block. Big files may either be split, or have a block that contains one file.
> 
>     * Option 3: variable block sizes

put apart that compressing per block reduces the compression ratio,  you did not solve the issue: your option 3 acts like a wildcard option, where "variable block sizes" looks like non-block approach. 
The more option you have, the more metadata you need to add to know the structure of your compressed data, and you precisely missed answering the question: "How then do you remember where is the data of each file?" 

> 
> > RAR "solid archives" seems to be exactly what tar does for compression
> 
>     * Yes, that's an important tar functionality. It's difficult to justify the switching cost from tar, if it performs worse on that aspect.

there is maybe no need to switch if you just need tar!

Dar has been built differently from tar to address three pitfalls found in tar when considered as a backup solution:
- tar backups are fragile: you lose everything that follows a data corruption, not only the file where the data corruption occurred
- you cannot save execution time by an important factor not compressing already compressed files 
- when you need to restore a particular file, you need to read the whole tar backup

As you seen dar optimizes both  **execution time** and **data availability** first, then compression. Tar does else.

But of course, the need to save any possible bits of storage also exists for long: already at the time of Windows 3.x (~1990) there was a software that compressed files on disk, this worked well, but made your PC so slow.... then disk capacity increased from Mega to Giga and nobody now cares that a Microsoft World document that just contains "Hello World" needs several hundred kilobytes on disk.

IMHO, the battle of disk space optimization is vain and outdated, and worse, dar is very close to tar most of the time [See the Dar, Tar, Rsync Benchmark](http://dar.linux.free.fr/doc/benchmark.html)

Last, the request you make of compressing small files together in dar backups is not recent [see FAQ](http://dar.linux.free.fr/doc/FAQ.html#Smallfiles) and still no one could give a concrete method of solving this problem, still keeping available the fundamental features dar has been built for.

**Comment by shaicoleman** [comment]
> this depends on algorithms
I'm only really interested in zstd, which has the best compression/performance balance.

> As you seen dar optimizes both execution time and data availability first, then compression. Tar does else.
The performance impact might be much smaller than you might think.
Nowadays mainstream NVMe can read at 5000MB/sec and zstd decompresses at 2000MB/sec.
The impact of having to read and decompress a 16MB block is dozens of microseconds.

Regarding data availability, worst case you'll lose 16MB of data, and not the whole file, which can be acceptable.
Data availability can be handled in different ways, e.g. PAR files, storage redundancy (Amazon S3), on the filesystem (ZFS). With modern hardware, total loss is way more likely than partial corruption, as drives have built-in error correction.

> still no one could give a concrete method of solving this problem
You can look at the restic implementation as I mentioned above.

Feel free to close this issue if you don't think it fits DAR

**Comment by Edrusb** [comment]
restic does not rely on a file format, but uses a directory tree (a repository). There is thus no much common things with dar or tar which both  have the constraint to serialize/de-serialize the data and metadata together.
