### ISSUE TITLE
Problem when build

### ISSUE THREAD

**Issue by lbazan** [Edrusb/DAR#6]
/ea_filesystem.Tpo -c ea_filesystem.cpp  -D__DYNAMIC__  -fPIC -DPIC -o .libs/ea_filesystem.o
ea_filesystem.cpp: In function 'bool libdar::remove_ea(const string&, const libdar::ea_attributs&, const libdar::mask&)':
ea_filesystem.cpp:215:15: error: 'ENOATTR' was not declared in this scope
   if(errno != ENOATTR)
               ^~~~~~~
ea_filesystem.cpp:215:15: note: suggested alternative: 'ENOTTY'
   if(errno != ENOATTR)
               ^~~~~~~
               ENOTTY
make[3]: *** [Makefile:1188: ea_filesystem.lo] Error 1

**Comment by Edrusb** [comment]
can't do anything with that info. If you need support please read http://dar.linux.free.fr/#support
