### ISSUE TITLE
Using Dar (2.7.14) on Windows with sub folders causes infinite loop unless output archive is excluded 

### ISSUE THREAD

**Issue by timdonovanuk** [Edrusb/DAR#61]
My test folder is 3mb.

![image](https://github.com/Edrusb/DAR/assets/8156439/36ddd1ea-3d38-479c-85d6-eba4e9e7b873)

`dar -c test.dar` will run forever until my drive is full or dar is killed:

![image](https://github.com/Edrusb/DAR/assets/8156439/331a9a21-d291-4b5e-9f7c-3273029aff4f)

An identical structure and identical command on linux (debian) runs as expected. 

I have found `dar -c test.dar -X "*.*.dar"` as a workaround (but you can't then dar...dar's)

Thanks!

**Comment by Edrusb** [comment]
release 2.7.15 is now available with fix for that issue
