### ISSUE TITLE
libgcrypt 1.11 has removed memory guard support, leading to fatal error

### ISSUE THREAD

**Issue by davdittrich** [Edrusb/DAR#62]
Libgcrypt 1.11 has removed support for memory guard, see https://dev.gnupg.org/T5822.

On systems whith libgcrypt 1.11 or never, dar now fails with
FATAL error, aborting operation: Error while activating libgcrypt's memory guard: gcrypt/Not supported

**Comment by Edrusb** [comment]
Hi Dennis, Thanks for yout feedback. The fix is available in git (tag 2.7.15.RC3) and will be released with version 2.7.15 at the end of next week. You can also download a tarball with associated package signature at https://dar.edrusb.org/dar.linux.free.fr/Interim_releases

**Comment by Edrusb** [comment]
release 2.7.15 is now available with fix for that issue
