### ISSUE TITLE
listing fields (columns)

### ISSUE THREAD

**Issue by AndrewDDavis** [Edrusb/DAR#63]
When using `dar --list ...`, is there a way to control the fields (columns) in the listing? I would like to show fewer fields than the default. With the default setting, the listing wraps across lines and is hard to read. My current workaround is to pipe to `less -S`.

**Comment by Edrusb** [comment]
Hi Andrew, sorry to have missed your support request (which are expected to be sent to the[ dar-support mailing-list](https://sourceforge.net/p/dar/mailman/))

the -T option let you change the listing output format but check if one of the three possible output better match your need, but to answer your question there is today no such option, unless by using the libdar API to get fine-customized listing field.

**Comment by Edrusb** [comment]
An alternative to directly using the API (from C or C++ code) is using the python binding to libdar (thus, from python code)...

**Comment by AndrewDDavis** [comment]
Ok, thanks
